apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-deployment
  template:
    metadata:
      labels:
        app: backend-deployment
    spec:
      containers:
      - name: backend
        image: nuwnjay/docker-synapse-server:v1
        # image: node
        ports:
          - containerPort: 3000
        imagePullPolicy: IfNotPresent
