apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  selector:
    app: backend-deployment
  ports:
  - port: 9000
    name: http
    targetPort: 9000
  - port: 443
    name: https
    targetPort: 9000