version: "3.9"

services:
    synapse:
        build: ./synapse/
        ports: 
            - "8280:8280"
        depends_on: 
            - "server"
        image: docker-synapse:v1
        
    server:
        build: ./server/
        # env_file: .
        ports: 
            - "3000:3000"
        image: docker-synapse-server:v1

    