version: "3.9"

services:
    synapse:
        build: ./synapse/
        ports: 
            - "8280:8280"
        image: nuwnjay/docker-synapse:v5

    server:
        build: ./axis2server/
        ports: 
            - "9000:9000"
        image: nuwnjay/docker-axis-server:v1
        
    # server:
    #     build: ./server/
    #     # env_file: .
    #     ports: 
    #         - "3000:3000"
    #     image: nuwnjay/docker-synapse-server:v1

    client:
        build: ./client/
        image: nuwnjay/docker-synapse-client:v1

    