kind: PersistentVolume
apiVersion: v1
metadata:
  name: synapse-persistent-volume
  labels:
    type: local
spec:
  storageClassName: pv-synapse 
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"